const DEFAULT_SIZE = 200;
const DEFAULT_OFF_COLOR = "#8369f5";
const DEFAULT_ON_COLOR = "#8369f5";
const DEFAULT_BLOB_COLOR = "#1F2937";
const DEFAULT_ICON_COLOR = "#FFFFFF";
const DEFAULT_THRESHOLD = 0.5;

export {
  DEFAULT_SIZE,
  DEFAULT_OFF_COLOR,
  DEFAULT_ON_COLOR,
  DEFAULT_BLOB_COLOR,
  DEFAULT_ICON_COLOR,
  DEFAULT_THRESHOLD,
};
